-- MySQL Script generated by MySQL Workbench
-- Sun May 16 21:39:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Locster
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Locster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Locster` DEFAULT CHARACTER SET utf8 ;
USE `Locster` ;

-- -----------------------------------------------------
-- Table `Locster`.`ONLINE_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`ONLINE_STATUS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`ONLINE_STATUS` (
                                                         `ID` INT NOT NULL AUTO_INCREMENT,
                                                         `DESCRIPTION` VARCHAR(45) NOT NULL,
                                                         PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`RELATIONSHIP_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`RELATIONSHIP_STATUS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`RELATIONSHIP_STATUS` (
                                                               `ID` INT NOT NULL AUTO_INCREMENT,
                                                               `DESCRIPTION` VARCHAR(45) NOT NULL,
                                                               PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`SEX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`SEX` ;

CREATE TABLE IF NOT EXISTS `Locster`.`SEX` (
                                               `ID` INT NOT NULL AUTO_INCREMENT,
                                               `DESCRIPTION` VARCHAR(45) NOT NULL,
                                               PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`PERSONAL_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`PERSONAL_INFO` ;

CREATE TABLE IF NOT EXISTS `Locster`.`PERSONAL_INFO` (
                                                         `ID` INT NOT NULL AUTO_INCREMENT,
                                                         `FIRST_NAME` VARCHAR(255) NOT NULL,
                                                         `LAST_NAME` VARCHAR(255) NOT NULL,
                                                         `REGION` VARCHAR(255) NULL,
                                                         `BIRTH_DATE` TIMESTAMP NULL,
                                                         `OCCUPATION` VARCHAR(255) NULL,
                                                         `RELATIONSHIP_STATUS_ID` INT NULL,
                                                         `PROFILE_PICTURE` VARCHAR(45) NULL,
                                                         `SEX_ID` INT NULL,
                                                         PRIMARY KEY (`ID`),
                                                         CONSTRAINT `fk_PERSONAL_INFO_RELATIONSHIP_STATUS1`
                                                             FOREIGN KEY (`RELATIONSHIP_STATUS_ID`)
                                                                 REFERENCES `Locster`.`RELATIONSHIP_STATUS` (`ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_PERSONAL_INFO_SEX1`
                                                             FOREIGN KEY (`SEX_ID`)
                                                                 REFERENCES `Locster`.`SEX` (`ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`ACCOUNT_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`ACCOUNT_DETAILS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`ACCOUNT_DETAILS` (
                                                           `ID` INT NOT NULL AUTO_INCREMENT,
                                                           `USER_NAME` VARCHAR(45) NOT NULL,
                                                           `MAIL_ADDRESS` VARCHAR(255) NULL,
                                                           `PASSWORD_HASH` VARCHAR(255) NOT NULL,
                                                           PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`PRIVACY_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`PRIVACY_STATUS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`PRIVACY_STATUS` (
                                                          `ID` INT NOT NULL AUTO_INCREMENT,
                                                          `DESCRIPTION` VARCHAR(45) NOT NULL,
                                                          PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`PROFILE_STATISTICS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`PROFILE_STATISTICS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`PROFILE_STATISTICS` (
                                                              `ID` INT NOT NULL AUTO_INCREMENT,
                                                              `VISITS_COUNT` INT NOT NULL,
                                                              `VISITORS_COUNT` INT NOT NULL,
                                                              PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`USER` ;

CREATE TABLE IF NOT EXISTS `Locster`.`USER` (
                                                `ID` INT NOT NULL AUTO_INCREMENT,
                                                `PERSONAL_INFO_ID` INT NOT NULL,
                                                `ACCOUNT_DETAILS_ID` INT NOT NULL,
                                                `PERSONAL_STATUS` VARCHAR(255) NULL,
                                                `PRIVACY_STATUS_ID` INT NOT NULL,
                                                `ONLINE_STATUS_ID` INT NOT NULL,
                                                `PROFILE_STATISTICS_ID` INT NOT NULL,
                                                PRIMARY KEY (`ID`),
                                                CONSTRAINT `fk_user_onlineStatus`
                                                    FOREIGN KEY (`ONLINE_STATUS_ID`)
                                                        REFERENCES `Locster`.`ONLINE_STATUS` (`ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_USER_PERSONAL_INFO1`
                                                    FOREIGN KEY (`PERSONAL_INFO_ID`)
                                                        REFERENCES `Locster`.`PERSONAL_INFO` (`ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_USER_ACCOUNT_DETAILS1`
                                                    FOREIGN KEY (`ACCOUNT_DETAILS_ID`)
                                                        REFERENCES `Locster`.`ACCOUNT_DETAILS` (`ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_USER_PRIVACY_STATUS1`
                                                    FOREIGN KEY (`PRIVACY_STATUS_ID`)
                                                        REFERENCES `Locster`.`PRIVACY_STATUS` (`ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_USER_PROFILE_STATISTICS1`
                                                    FOREIGN KEY (`PROFILE_STATISTICS_ID`)
                                                        REFERENCES `Locster`.`PROFILE_STATISTICS` (`ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`FRIENDSHIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`FRIENDSHIP` ;

CREATE TABLE IF NOT EXISTS `Locster`.`FRIENDSHIP` (
                                                      `ID` INT NOT NULL AUTO_INCREMENT,
                                                      `SENDER_ID` INT NOT NULL,
                                                      `RECEIVER_ID` INT NOT NULL,
                                                      `FRIEND_SINCE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      `IS_ACCEPTED` TINYINT NULL,
                                                      PRIMARY KEY (`ID`),
                                                      CONSTRAINT `fk_FRIENDLIST_ITEM_USER1`
                                                          FOREIGN KEY (`SENDER_ID`)
                                                              REFERENCES `Locster`.`USER` (`ID`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_FRIENDLIST_ITEM_USER2`
                                                          FOREIGN KEY (`RECEIVER_ID`)
                                                              REFERENCES `Locster`.`USER` (`ID`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`GUESTBOOK_ENTRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`GUESTBOOK_ENTRY` ;

CREATE TABLE IF NOT EXISTS `Locster`.`GUESTBOOK_ENTRY` (
                                                           `ID` INT NOT NULL AUTO_INCREMENT,
                                                           `CREATOR_ID` INT NOT NULL,
                                                           `RECEIVER_ID` INT NOT NULL,
                                                           `TEXT` VARCHAR(255) NULL,
                                                           `SENT_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           `EDITED_AT` TIMESTAMP NULL,
                                                           `EDITED` TINYINT ZEROFILL NOT NULL DEFAULT 0,
                                                           PRIMARY KEY (`ID`),
                                                           CONSTRAINT `fk_GUESTBOOK_ENTRY_USER1`
                                                               FOREIGN KEY (`CREATOR_ID`)
                                                                   REFERENCES `Locster`.`USER` (`ID`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_GUESTBOOK_ENTRY_USER2`
                                                               FOREIGN KEY (`RECEIVER_ID`)
                                                                   REFERENCES `Locster`.`USER` (`ID`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`CHAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`CHAT` ;

CREATE TABLE IF NOT EXISTS `Locster`.`CHAT` (
                                                `ID` INT NOT NULL AUTO_INCREMENT,
                                                `NAME` VARCHAR(255) NULL,
                                                PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `Locster`.`USER_CHAT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`USER_CHAT` ;

CREATE TABLE IF NOT EXISTS `Locster`.`USER_CHAT` (
                                                     `ID` INT NOT NULL AUTO_INCREMENT,
                                                     `USER_ID` INT NOT NULL,
                                                     `CHAT_ID` INT NOT NULL,
                                                     PRIMARY KEY (`ID`),
                                                     CONSTRAINT `fk_USER_CHAT_USER1`
                                                         FOREIGN KEY (`USER_ID`)
                                                             REFERENCES `Locster`.`USER` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_USER_CHAT_CHAT1`
                                                         FOREIGN KEY (`CHAT_ID`)
                                                             REFERENCES `Locster`.`CHAT` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`MESSAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`MESSAGE` ;

CREATE TABLE IF NOT EXISTS `Locster`.`MESSAGE` (
                                                   `ID` INT NOT NULL AUTO_INCREMENT,
                                                   `SENDER_ID` INT NOT NULL,
                                                   `TEXT` VARCHAR(255) NOT NULL,
                                                   `SENT_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                   `CHAT_ID` INT NOT NULL,
                                                   PRIMARY KEY (`ID`),
                                                   CONSTRAINT `fk_MESSAGE_USER1`
                                                       FOREIGN KEY (`SENDER_ID`)
                                                           REFERENCES `Locster`.`USER` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_MESSAGE_CHAT1`
                                                       FOREIGN KEY (`CHAT_ID`)
                                                           REFERENCES `Locster`.`CHAT` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`VISITS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`VISITS` ;

CREATE TABLE IF NOT EXISTS `Locster`.`VISITS` (
                                                  `ID` INT NOT NULL AUTO_INCREMENT,
                                                  `VISTOR_ID` INT NOT NULL,
                                                  `VISITED_USER_ID` INT NOT NULL,
                                                  `TIME_OF_VISIT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                  PRIMARY KEY (`ID`),
                                                  CONSTRAINT `fk_VISITS_USER1`
                                                      FOREIGN KEY (`VISTOR_ID`)
                                                          REFERENCES `Locster`.`USER` (`ID`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_VISITS_USER2`
                                                      FOREIGN KEY (`VISITED_USER_ID`)
                                                          REFERENCES `Locster`.`USER` (`ID`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Locster`.`READ_BY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Locster`.`READ_BY` ;

CREATE TABLE IF NOT EXISTS `Locster`.`READ_BY` (
                                                   `ID` INT NOT NULL AUTO_INCREMENT,
                                                   `MESSAGE_ID` INT NOT NULL,
                                                   `USER_ID` INT NOT NULL,
                                                   PRIMARY KEY (`ID`),
                                                   CONSTRAINT `fk_READ_BY_MESSAGE1`
                                                       FOREIGN KEY (`MESSAGE_ID`)
                                                           REFERENCES `Locster`.`MESSAGE` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_READ_BY_USER1`
                                                       FOREIGN KEY (`USER_ID`)
                                                           REFERENCES `Locster`.`USER` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
